module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        navbtn: "#FFEDED",
        darkblue: "#0F4A7B",
        lightskyblue: "#E5E5E5",
        lighterskyblue: "#F9FBFD",
        lightcyan: "#62BECB",
        primary: "#EA5566",
        lightblue: "#b4c4ed",
      },
      spacing: {
        sm: "130px",
        lg: "140px",
        sxl: "200px",
        xl: "250px",
        xxl: "310px",
        xxxl: "500px",
        "12.5%": "12.5%",
        "5%": "5%",
        250: "250px",
        320: "320px",
        80: "80px",
        50: "50px",
        70: "70px",
      },
      height: {
        "3xl": "560px",
        xxl: "520px",
        xl: "320px",
        lg: "120px",
        md: "60px",
        sm: "50px",
        840: "840px",
      },
      width: {
        lg: "120px",
        md: "60px",
        sm: "50px",
        80: "80px",
        forty: "40%",
        ninety: "90%",
        "50%": "50%",
      },
    },
  },
  plugins: [
    require("@tailwindcss/line-clamp"),
    require("tailwind-scrollbar-hide"),
    require("@tailwindcss/typography"),
  ],
};
